// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Gary Frattarola <garycoding@gmail.com>
import { app, BrowserWindow, Menu, ipcMain, dialog, shell, session } from 'electron'
import { join } from 'path'
import { readFileSync, existsSync } from 'fs'
import { pathToFileURL, fileURLToPath } from 'node:url'
import pkg from '../../package.json'
import {
  getSettings, setLastDomain, getLibraryRoot, setLibraryRoot,
  listDomains, createForest, loadForest, saveForest, readNote, writeNote, deleteNote,
} from './store.js'

const isDev = !app.isPackaged
const GITHUB_URL = 'https://github.com/garycoding/TaskForkStack'

function createWindow() {
  const win = new BrowserWindow({
    width: 1280,
    height: 800,
    backgroundColor: '#d3e6ef',
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      // The preload uses only contextBridge + ipcRenderer, both sandbox-safe, so
      // keep the renderer inside the OS sandbox to limit a compromise's reach.
      sandbox: true,
    },
  })

  // Never open a child window in-app; route http(s) to the system browser and
  // deny everything else (the About/Licenses windows are created directly, not
  // via window.open, so this does not affect them).
  win.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:\/\//i.test(url)) shell.openExternal(url)
    return { action: 'deny' }
  })

  const devUrl = process.env['ELECTRON_RENDERER_URL']
  if (isDev && devUrl) {
    win.loadURL(devUrl)
  } else {
    win.loadFile(join(__dirname, '../renderer/index.html'))
  }

  return win
}

// The renderer's Content-Security-Policy. In production it is strict — no remote
// anything, so an injected script (belt to the note sanitiser) cannot exfiltrate
// via fetch; 'unsafe-inline' for styles is required because the app, CodeMirror,
// and KaTeX all set element styles. In dev it is loosened for the Vite dev
// server and its HMR websocket.
function contentSecurityPolicy() {
  if (isDev) {
    return "default-src 'self' 'unsafe-inline' data: blob:; " +
      "script-src 'self' 'unsafe-inline' 'unsafe-eval'; " +
      "connect-src 'self' ws://localhost:* http://localhost:*; " +
      "img-src 'self' data: blob:; font-src 'self' data:"
  }
  return "default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; " +
    "img-src 'self' data:; font-src 'self' data:; connect-src 'self'; " +
    "base-uri 'none'; form-action 'none'"
}

let _aboutWin = null
function openAboutWindow() {
  if (_aboutWin && !_aboutWin.isDestroyed()) { _aboutWin.focus(); return }
  const html = `<!doctype html>
<meta charset="utf-8">
<style>
  html,body{margin:0;height:100%;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
    background:#111116;color:#e9e9ec;-webkit-user-select:none;cursor:default}
  .wrap{height:100%;box-sizing:border-box;padding:30px 34px;display:flex;flex-direction:column;
    align-items:center;justify-content:center;text-align:center}
  h1{margin:0;font-size:21px;font-weight:600;letter-spacing:.2px}
  .ver{margin:3px 0 18px;font-size:12px;color:#9494a0}
  .copy{margin:20px 0 12px;font-size:11px;color:#85859090}
  a{color:#4fc3f7;text-decoration:none;font-size:12px}
  a:hover{text-decoration:underline}
</style>
<div class="wrap">
  <h1>TaskForkStack</h1>
  <div class="ver">Version ${pkg.version}</div>
  <div class="copy">© 2026 Gary Frattarola — AGPL-3.0-or-later, or commercial</div>
  <a href="${GITHUB_URL}" target="_blank" rel="noopener">Source code on GitHub</a>
</div>`
  _aboutWin = new BrowserWindow({
    width: 420, height: 280,
    resizable: false, minimizable: false, maximizable: false, fullscreenable: false,
    backgroundColor: '#111116',
    title: 'About TaskForkStack',
    webPreferences: { contextIsolation: true, sandbox: true },
  })
  _aboutWin.setMenuBarVisibility(false)
  _aboutWin.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(html))
  _aboutWin.webContents.setWindowOpenHandler(({ url }) => { shell.openExternal(url); return { action: 'deny' } })
  _aboutWin.webContents.on('will-navigate', (e, url) => { e.preventDefault(); shell.openExternal(url) })
  _aboutWin.on('closed', () => { _aboutWin = null })
}

// The packaged legal/ notice bundle (generated by `npm run legal`). In dev it's
// the repo root; in the packaged app it's process.resourcesPath/legal.
function legalDir() {
  return app.isPackaged ? join(process.resourcesPath, 'legal') : join(__dirname, '../../legal')
}

// Marquee components called out at the top of the licenses window. Versions and
// links for production packages come from oss-licenses.json; electron is a build
// dependency (its Chromium/Node notices live in LICENSES.chromium.html).
const LICENSE_HIGHLIGHTS = [
  { pkg: 'electron', label: 'Electron', role: 'Desktop app runtime (Chromium + Node.js)',
    note: 'MIT · bundles Chromium + Node.js', repo: 'https://github.com/electron/electron' },
  { pkg: 'json5', label: 'JSON5', role: 'Reads and writes the forest files' },
  { pkg: 'codemirror', label: 'CodeMirror', role: 'The in-app note editor' },
  { pkg: 'marked', label: 'Marked', role: 'Renders note markdown' },
  { pkg: 'katex', label: 'KaTeX', role: 'Math typesetting in notes' },
]

let _licWin = null
function openLicensesWindow() {
  if (_licWin && !_licWin.isDestroyed()) { _licWin.focus(); return }
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]))
  const dir = legalDir()
  const listPath = join(dir, 'oss-licenses.json')
  const noticesHref = esc(pathToFileURL(join(dir, 'THIRD-PARTY-NOTICES.txt')).href)
  const chromiumHref = esc(pathToFileURL(join(dir, 'LICENSES.chromium.html')).href)

  let body
  if (existsSync(listPath)) {
    const list = JSON.parse(readFileSync(listPath, 'utf-8'))
    const byName = Object.fromEntries(list.map((p) => [p.name, p]))
    const cards = LICENSE_HIGHLIGHTS.map((h) => {
      const p = byName[h.pkg]
      const meta = h.note || (p ? `${esc(p.license)}${p.version ? ' · v' + esc(p.version) : ''}` : '')
      const repo = (p && p.repository) || h.repo || null
      const link = repo ? ` · <a href="${esc(repo)}" target="_blank" rel="noopener">repo</a>` : ''
      return `<div class="card"><div class="hn">${esc(h.label)}</div><div class="hr">${esc(h.role)}</div><div class="hm">${meta}${link}</div></div>`
    }).join('')
    const rows = list.map((p) => {
      const name = p.repository
        ? `<a href="${esc(p.repository)}" target="_blank" rel="noopener">${esc(p.name)}</a>`
        : esc(p.name)
      return `<tr><td>${name}</td><td class="m">${esc(p.version)}</td><td class="m">${esc(p.license)}</td></tr>`
    }).join('')
    body =
      `<div class="st">Key components</div><div class="cards">${cards}</div>` +
      `<div class="st">All bundled packages (${list.length})</div>` +
      `<table><thead><tr><th>Package</th><th>Version</th><th>License</th></tr></thead><tbody>${rows}</tbody></table>` +
      `<p class="foot">Chromium &amp; Node.js notices: <a href="${chromiumHref}" target="_blank" rel="noopener">LICENSES.chromium.html</a> · ` +
      `full per-package texts: <a href="${noticesHref}" target="_blank" rel="noopener">THIRD-PARTY-NOTICES.txt</a></p>`
  } else {
    body =
      `<div class="missing">License notices are generated at package time.<br>` +
      `Run <code>npm run legal</code> in the project root, then reopen this window.</div>`
  }

  const html = `<!doctype html><meta charset="utf-8"><title>Open Source Licenses</title><style>
  :root{--bg:#0a1622;--panel:#0f1f30;--line:rgba(255,255,255,.12);--accent:#4fc3f7}
  *{box-sizing:border-box}
  html,body{margin:0;height:100%}
  body{background:var(--bg);color:rgba(255,255,255,.8);font-size:13px;display:flex;flex-direction:column;
    font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif}
  header{padding:16px 22px 13px;border-bottom:1px solid var(--line);flex-shrink:0}
  h1{margin:0;font-size:13px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:rgba(255,255,255,.6)}
  .sub{margin-top:5px;font-size:12px;color:rgba(255,255,255,.4)}
  main{flex:1;overflow-y:auto;padding:2px 22px 26px;user-select:text;-webkit-user-select:text}
  .st{font-size:10px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:rgba(255,255,255,.38);margin:20px 0 10px}
  .cards{display:flex;flex-direction:column;gap:8px}
  .card{background:var(--panel);border:1px solid var(--line);border-radius:4px;padding:9px 13px}
  .hn{font-size:13px;font-weight:600;color:rgba(255,255,255,.9)}
  .hr{font-size:12px;color:rgba(255,255,255,.5);margin:1px 0 3px}
  .hm{font-size:11px;color:rgba(255,255,255,.42)}
  table{width:100%;border-collapse:collapse}
  th,td{border:1px solid var(--line);padding:5px 11px;text-align:left;font-size:12px}
  th{background:rgba(255,255,255,.06);color:rgba(255,255,255,.5);font-weight:600;letter-spacing:.04em}
  td{color:rgba(255,255,255,.72)} td.m{color:rgba(255,255,255,.45);white-space:nowrap}
  a{color:var(--accent);text-decoration:none} a:hover{text-decoration:underline}
  .foot{margin:18px 0 0;font-size:11px;color:rgba(255,255,255,.4);line-height:1.7}
  .missing{padding:48px 0;text-align:center;color:rgba(255,255,255,.4);line-height:1.9}
  code{background:rgba(255,255,255,.08);padding:1px 6px;border-radius:3px}
</style>
<header><h1>Open Source Licenses</h1><div class="sub">TaskForkStack includes the open-source software below.</div></header>
<main>${body}</main>`

  _licWin = new BrowserWindow({
    width: 720, height: 640, minWidth: 460, minHeight: 360,
    backgroundColor: '#0a1622',
    title: 'Open Source Licenses',
    webPreferences: { contextIsolation: true, sandbox: true },
  })
  _licWin.setMenuBarVisibility(false)
  _licWin.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(html))
  const openLink = (url) => { url.startsWith('file:') ? shell.openPath(fileURLToPath(url)) : shell.openExternal(url) }
  _licWin.webContents.setWindowOpenHandler(({ url }) => { openLink(url); return { action: 'deny' } })
  _licWin.webContents.on('will-navigate', (e, url) => { e.preventDefault(); openLink(url) })
  _licWin.on('closed', () => { _licWin = null })
}

function buildMenu() {
  const template = [
    ...(process.platform === 'darwin' ? [{
      label: app.name,
      submenu: [
        { label: `About ${app.name}`, click: () => openAboutWindow() },
        { label: 'Open Source Licenses…', click: () => openLicensesWindow() },
        { type: 'separator' },
        { role: 'services' },
        { type: 'separator' },
        { role: 'hide' },
        { role: 'hideOthers' },
        { role: 'unhide' },
        { type: 'separator' },
        { role: 'quit' },
      ],
    }] : []),
    { role: 'fileMenu' },
    { role: 'editMenu' },
    { role: 'viewMenu' },
    { role: 'windowMenu' },
    {
      role: 'help',
      submenu: [
        ...(process.platform !== 'darwin'
          ? [{ label: `About ${app.name}`, click: () => openAboutWindow() }, { type: 'separator' }]
          : []),
        { label: 'Open Source Licenses…', click: () => openLicensesWindow() },
        { label: 'Source Code on GitHub', click: () => shell.openExternal(GITHUB_URL) },
      ],
    },
  ]
  Menu.setApplicationMenu(Menu.buildFromTemplate(template))
}

app.whenReady().then(() => {
  const csp = contentSecurityPolicy()
  session.defaultSession.webRequest.onHeadersReceived((details, cb) => {
    cb({ responseHeaders: { ...details.responseHeaders, 'Content-Security-Policy': [csp] } })
  })

  const win = createWindow()
  buildMenu()

  // Persistence bridge: the renderer's whole view of disk. Handlers in store.js
  // re-derive and bounds-check every path against the library root.
  ipcMain.handle('tfs:get-settings',    () => getSettings())
  ipcMain.handle('tfs:set-last-domain', (_e, name) => setLastDomain(name))
  ipcMain.handle('tfs:get-library-root', () => getLibraryRoot())
  ipcMain.handle('tfs:choose-library-root', async () => {
    const { canceled, filePaths } = await dialog.showOpenDialog(win, {
      title: 'Choose a forest library folder',
      properties: ['openDirectory', 'createDirectory'],
    })
    if (canceled || !filePaths[0]) return { canceled: true }
    return setLibraryRoot(filePaths[0])
  })
  ipcMain.handle('tfs:list-domains',  () => listDomains())
  ipcMain.handle('tfs:create-forest', (_e, name) => createForest(name))
  ipcMain.handle('tfs:load-forest',   (_e, dir) => loadForest(dir))
  ipcMain.handle('tfs:save-forest',   (_e, dir, text) => saveForest(dir, text))
  ipcMain.handle('tfs:read-note',     (_e, dir, file) => readNote(dir, file))
  ipcMain.handle('tfs:write-note',    (_e, dir, file, text) => writeNote(dir, file, text))
  ipcMain.handle('tfs:delete-note',   (_e, dir, file) => deleteNote(dir, file))
  ipcMain.handle('tfs:open-external', (_e, url) => {
    if (typeof url === 'string' && /^https?:\/\//i.test(url)) shell.openExternal(url)
  })

  // Safety net: keep the window from navigating away from the app; open any
  // external URL that slips through in the system browser instead.
  win.webContents.on('will-navigate', (e, url) => {
    // Compare against the real file URL (pathToFileURL) rather than a hand-built
    // 'file://' + OS path, which is malformed on Windows (backslashes, drive
    // letter, two slashes) and would treat the app's own URL as external.
    const appUrl = isDev
      ? process.env['ELECTRON_RENDERER_URL']
      : pathToFileURL(join(__dirname, '../renderer/index.html')).href
    if (appUrl && !url.startsWith(appUrl)) {
      e.preventDefault()
      shell.openExternal(url)
    }
  })

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
